# Render a pairing's schema coverage as a markdown table, as a build artifact.
#
# why: two jobs at once. Building it forces the generator's drift assertions on
# their own, so `nix flake check` reports schema drift as a named failing check
# instead of burying it inside a VM test. And the output is the review artifact
# for "what does this pairing actually cover?" -- which resources are modelled,
# which are deliberately not, and how much of each resource's surface survives
# the overlay's corrections.
{ pkgs }:
let
  inherit (pkgs) lib;

  # markdown table cell for a list: `a`, `b` -- or an em dash when empty.
  cell = xs: if xs == [ ] then "--" else lib.concatMapStringsSep ", " (x: "`${x}`") xs;
in
{
  # name      pairing name, used for the output file and the heading
  # coverage  the `coverage` attrset returned by ./tf-schema.nix
  mkCoverageReport =
    { name, coverage }:
    let
      modelled = lib.length (lib.attrNames coverage.collections);

      row =
        collection: c:
        "| `${collection}` | `${c.type}` | ${toString c.options} of ${toString c.attributes} | ${cell c.secrets} | ${cell c.refs} | ${cell c.omitted} |";

      unsupportedSection =
        if coverage.unsupported == { } then
          "Every resource the provider offers is modelled.\n"
        else
          ''
            | Provider resource | Reason |
            | --- | --- |
            ${lib.concatStringsSep "\n" (
              lib.mapAttrsToList (type: reason: "| `${type}` | ${reason} |") coverage.unsupported
            )}
          '';
    in
    pkgs.writeText "${name}-schema-coverage.md" ''
      # ${name} runtime resource coverage

      Derived from `services/${name}/provider-schema.json`; regenerated by
      `nix build .#checks.<system>.${name}-schema-coverage`. Do not edit.

      Provider `${coverage.source}` ${coverage.version}: ${toString modelled} of ${toString coverage.schemaResources} resources modelled.

      `Options` counts a collection's top-level options against the settable
      top-level attributes the provider schema declares for it; the two differ
      exactly by the attributes consumed by references and by `Omitted`. Nested
      block attributes are options of their own submodule and are not counted
      here.

      ## Modelled

      | `${coverage.runtimePrefix}.<collection>` | Provider resource | Options | Secrets | References | Omitted |
      | --- | --- | --- | --- | --- | --- |
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList row coverage.collections)}

      ## Not modelled

      ${unsupportedSection}
    '';
}
