name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          # nspawn container tests need auto-allocate-uids + cgroups.
          extra-conf: |
            extra-experimental-features = auto-allocate-uids cgroups
            auto-allocate-uids = true
            use-cgroups = true

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix flake check
        run: nix flake check -L
